### ISSUE TITLE
No report XML or HTML created

### ISSUE THREAD

**Issue by Kxa422** [forcedotcom/ApexUnit#42]
At the end of the test process, the following error appear and no XML or HTML reports are created 

Jun 22, 2016 2:33:21 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jun 22, 2016 2:33:22 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Jun 22, 2016 2:33:22 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jun 22, 2016 2:33:22 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Jun 22, 2016 2:33:22 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jun 22, 2016 2:33:22 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Exception during post method: java.net.BindException: Permission denied
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithErrMsg(ApexUnitUtils.java:68)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithDebugLog(ApexUnitUtils.java:53)
	at com.sforce.cd.apexUnit.client.codeCoverage.WebServiceInvoker.doPost(WebServiceInvoker.java:107)
	at com.sforce.cd.apexUnit.client.codeCoverage.OAuthTokenGenerator.doPostAndGetOrgToken(OAuthTokenGenerator.java:68)
	at com.sforce.cd.apexUnit.client.codeCoverage.OAuthTokenGenerator.getOrgToken(OAuthTokenGenerator.java:55)
	at com.sforce.cd.apexUnit.client.codeCoverage.CodeCoverageComputer.calculateAggregatedCodeCoverageUsingToolingAPI(CodeCoverageComputer.java:124)
	at com.sforce.cd.apexUnit.ApexUnitRunner.main(ApexUnitRunner.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)

**Comment by glang** [comment]
Hi @Kxa422 , are you still facing this issue?

**Comment by Kxa422** [comment]
Bug is not solved

**Comment by glang** [comment]
Hi @Kxa422 , I'll be looking into this for you. Can you provide as much detail as you can on how you are running ApexUnit?

**Comment by Kxa422** [comment]
I'm making a git clone of https://github.com/forcedotcom/ApexUnit.git

After that, I'm running the following from Maven 
compile exec:java -Dexec.mainClass="com.sforce.cd.apexUnit.ApexUnitRunner" -Dexec.args=" -org.login.url https://na15.salesforce.com -org.username MyUser@MyDomain.com -org.password MyPasswordAndMySecurityToken -org.wide.code.coverage.threshold 75  -team.code.coverage.threshold 80 -org.client.id MyClientId -org.client.secret MyClientSecret -regex.for.selecting.test.classes.to.execute * -regex.for.selecting.source.classes.for.code.coverage.computation *"

It starting well like

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ApexUnit 2.3.4
[INFO] ------------------------------------------------------------------------

Close to the end the following appear

[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.TestStatusPollerAndResultHandler - All tests have now completed executing!!
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitRunner - ####################################    Computing code coverage for the team based on the Apex Class names(source class names) provided  #################################### 
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex(es): * to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex: "*" to fetch apex classes

And the problem appear

Jul 02, 2016 7:36:09 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jul 02, 2016 7:36:09 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Jul 02, 2016 7:36:09 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jul 02, 2016 7:36:09 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Jul 02, 2016 7:36:09 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jul 02, 2016 7:36:09 AM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Exception during post method: java.net.BindException: Permission denied
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1365)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithErrMsg(ApexUnitUtils.java:68)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithDebugLog(ApexUnitUtils.java:53)
	at com.sforce.cd.apexUnit.client.codeCoverage.WebServiceInvoker.doPost(WebServiceInvoker.java:107)
	at com.sforce.cd.apexUnit.client.codeCoverage.OAuthTokenGenerator.doPostAndGetOrgToken(OAuthTokenGenerator.java:68)
	at com.sforce.cd.apexUnit.client.codeCoverage.OAuthTokenGenerator.getOrgToken(OAuthTokenGenerator.java:55)
	at com.sforce.cd.apexUnit.client.codeCoverage.CodeCoverageComputer.calculateAggregatedCodeCoverageUsingToolingAPI(CodeCoverageComputer.java:124)
	at com.sforce.cd.apexUnit.ApexUnitRunner.main(ApexUnitRunner.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)

**Comment by glang** [comment]
Looks like this could potentially be an OAuth setting issue. Could you run this line (replacing the items in the line with your maven arguments) in your terminal and report back? 

curl -v <Salesforce_Org_URL>/services/oauth2/token -d "grant_type=password" -d "client_id=***************************************" -d "client_secret= **************" -d "username=***********" -d "password= *******"

**Comment by Kxa422** [comment]
* Adding handle: conn: 0x25b8ab0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x25b8ab0) send_pipe: 1, recv_pipe: 0
* About to connect() to na15.salesforce.com port 443 (#0)
*   Trying 96.43.150.216...
* Connected to na15.salesforce.com (96.43.150.216) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA
* Server certificate:
*        subject: C=US; ST=California; L=San Francisco; O=Salesforce.com, Inc; OU=Applications; CN=*.salesforce.com
*        start date: 2015-02-14 00:00:00 GMT
*        expire date: 2018-02-14 23:59:59 GMT
*        subjectAltName: na15.salesforce.com matched
*        issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
*        SSL certificate verify ok.
> POST /services/oauth2/token HTTP/1.1
> User-Agent: curl/7.30.0
> Host: na15.salesforce.com
> Accept: */*
> Content-Length: 222
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 222 out of 222 bytes
< HTTP/1.1 400 Bad Request
< Date: Tue, 05 Jul 2016 21:36:12 GMT
< Set-Cookie: BrowserId=rInlegFeTnOUIAnwsfhdow;Path=/;Domain=.salesforce.com;Expires=Sat, 03-Sep-2016 21:36:12 GMT
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Pragma: no-cache
< Cache-Control: no-cache, no-store
< X-ReadOnlyMode: false
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
<

**Comment by glang** [comment]
Thanks, @Kxa422 . One thing that stands out to me if the "HTTP/1.1 400 Bad Request". Can you confirm that your credentials are setup correctly? Here is a guide that walks though the process.

**Comment by Kxa422** [comment]
Hello,

Credentials are working fine, if it was not the case the test cases were not submitted :-)
That issue could be related to Java version, if I'm using Java 8 on a local computer it's working as expected, if I'm using a server (Can't update that one) with Java 7, the error appear.

**Comment by glang** [comment]
@Kxa422 Interesting. I will continue looking into this and let you know when I find something. You wouldn't happen to be a salesforce employee, would you?

**Comment by glang** [comment]
@Kxa422 Does your password, username, or clientid happen to contain any special characters like '#', "$', or '%'? We recently discovered an issue with special characters.

**Comment by Kxa422** [comment]
# is part of my password

**Comment by glang** [comment]
@Kxa422 Ah, the bug with special characters may have played a role in your issue then. I have submitted a pull request for a fix and it should be merged before the end of the day. I'll let you know when that happens :)

**Comment by glang** [comment]
@Kxa422 The fix for the password encoding issue has been merged! Please try pulling the latest version of this project and let me know if that resolves your issue :)

**Comment by Kxa422** [comment]
No, the issue is still there

**Comment by glang** [comment]
@Kxa422 Interesting. Would you mind running this curl command again:
curl -v <Salesforce_Org_URL>/services/oauth2/token -d "grant_type=password" -d "client_id=***************************************" -d "client_secret= **************" -d "username=***********" -d "password= *******"
But run it one time with your password as it is, and another time running your password after it has been encoded to the UTF-8 format? You can encode your password using this website: http://www.url-encode-decode.com/ which converts it to a text format that is compatible with a url. Lastly, would you mind posting the console output of your apexunit run as well? Thanks!

**Comment by Kxa422** [comment]
From Curl

* Adding handle: conn: 0x25a7fc0
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x25a7fc0) send_pipe: 1, recv_pipe: 0
* About to connect() to na15.salesforce.com port 443 (#0)
*   Trying 96.43.150.216...
* Connected to na15.salesforce.com (96.43.150.216) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: C:\Users\jean-noel\AppData\Local\Atlassian\SourceTree\git_local\bin\curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using AES256-SHA
* Server certificate:
*        subject: C=US; ST=California; L=San Francisco; O=Salesforce.com, Inc; OU=Applications; CN=*.salesforce.com
*        start date: 2015-02-14 00:00:00 GMT
*        expire date: 2018-02-14 23:59:59 GMT
*        subjectAltName: na15.salesforce.com matched
*        issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
*        SSL certificate verify ok.
> POST /services/oauth2/token HTTP/1.1
> User-Agent: curl/7.30.0
> Host: na15.salesforce.com
> Accept: */*
> Content-Length: 226
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 226 out of 226 bytes
< HTTP/1.1 400 TLS 1.1 or higher required
< Date: Fri, 15 Jul 2016 19:08:33 GMT
< Set-Cookie: BrowserId=QvOSCnihT36fHQuMIXosvQ;Path=/;Domain=.salesforce.com;Expires=Tue, 13-Sep-2016 19:08:33 GMT
< X-ReadOnlyMode: false
< Content-Type: text/html;charset=UTF-8
< Cache-Control: no-cache, must-revalidate, max-age=0, no-store, private
< Pragma: no-cache
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Transfer-Encoding: chunked
<

<!DOCTYPE html><html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<title>Stronger security is required</title>
<style>
@font-face{
    font-family:'SalesforceSansLight';src:url('https://www.salesforce.com/system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Light.eot');
    src:url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Light.eot?#iefix') format('embedded-opentype'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Light.woff') format('woff'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Light.woff2') format('woff2'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Light.ttf') format('truetype'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Light.svg#SalesforceSansLight') format('svg');
        font-weight:normal;
        font-style:normal;
}
@font-face{
    font-family:'SalesforceSansRegular';
    src:url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.eot');
    src:url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.eot?#iefix') format('embedded-opentype'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.woff') format('woff'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.woff2') format('woff2'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.ttf') format('truetype'),
        url('https://secure2.sfdcstatic.com//system/shared/common/assets/fonts/SalesforceSans/SalesforceSans-Regular.svg#SalesforceSansRegular') format('svg');
        font-weight:normal;
        font-style:normal;
}
img{
    border:0px;vertical-align:text-bottom;
}
body {
    font-family:SalesforceSansRegular, Helvetica Neue, Helvetica, Arial;
    height:100%;
    margin:0px;
}
a {
    text-decoration:none;
    color:#0070d2;
}
html {
    height:100%;
}
h1 {
    font-family:SalesforceSansLight, Helvetica Neue, Helvetica, Arial;
    font-size:2em;
    font-weight:normal;
    text-align:center;
    margin-top:0px;
}
p {
    font-size:.875em;
    line-height:1.5em;
    margin:0px 0px .75em 0px;
}
p:last-child {
    margin:0px;
}
table {
    margin:0px;
    padding:0px;
}
.iebox {
    width:100%;
    text-align:left;
    background-color:#F4F6F9;
    border: 1px solid #D8DDE6;
    border-width:1px;
    padding:1.5em;
    margin-left:-1.5em;
    border-radius:.25em;
    -moz-border-radius:.25em;
    -webkit-border-radius:.25em;
    margin-bottom:.75em;
}
.simple {
    text-align:center;
}
.content {
    width:50%;
    padding-left:25%;
}
</style>
<meta http-equiv="X-UA-Compatible" content="IE=9" />
</head>
<body>
<table width="100%" height="100%" border="0">
<tr><td width="100%" height="100%"><div class="content"><h1>Stronger security is required</h1><div class="simple"><p>To access this website, update your web browser or upgrade your operating system to support TLS 1.1 or TLS 1.2.</p><p>For more information, see <a href="https://help.salesforce.com/HTViewSolution?id=000221207&amp;language=en_US" target="_blank">Salesforce disabling TLS 1.0</a>.
</p></div></div></td></tr>
</table></body>
</html>
* Connection #0 to host na15.salesforce.com left intact

**Comment by Kxa422** [comment]
From the output

com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.connection.PartnerConnectionConnectorConfig - Updated connection time out value(from config.properties file): 1200000
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex(es): * to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex: "*" to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.connection.ConnectionHandler - Bulk connection established.
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler - Creating batch for the test classes to execute using bulk connection....
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler - Async test parent job Id : 707i000005TDSvRAAX
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.AsyncBulkApiHandler - ############################# List of Apex test classes successfully submitted to the Force.com test execution engine #############################
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.TestExecutor - Parent job ID for the submission of the test classes to the Force.com platform is: 707i000005TDSvRAAX
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.TestExecutor - ############################# Now executing - Apex tests.. #############################
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.TestStatusPollerAndResultHandler - Total test classes to execute: 83

And all test appear

[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.testEngine.TestStatusPollerAndResultHandler - All tests have now completed executing!!
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitRunner - ####################################    Computing code coverage for the team based on the Apex Class names(source class names) provided  #################################### 
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex(es): * to fetch apex classes
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.client.utils.ApexClassFetcherUtils - Using regex: "*" to fetch apex classes
Jul 15, 2016 2:23:08 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jul 15, 2016 2:23:08 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Jul 15, 2016 2:23:08 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jul 15, 2016 2:23:08 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
Jul 15, 2016 2:23:08 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (java.net.BindException) caught when processing request: Permission denied
Jul 15, 2016 2:23:08 PM org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: Retrying request
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] ERROR com.sforce.cd.apexUnit.ApexUnitUtils - Exception during post method: java.net.BindException: Permission denied
[com.sforce.cd.apexUnit.ApexUnitRunner.main()] INFO com.sforce.cd.apexUnit.ApexUnitUtils - Shutting down ApexUnit
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1329)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithErrMsg(ApexUnitUtils.java:68)
	at com.sforce.cd.apexUnit.ApexUnitUtils.shutDownWithDebugLog(ApexUnitUtils.java:53)
	at com.sforce.cd.apexUnit.client.codeCoverage.WebServiceInvoker.doPost(WebServiceInvoker.java:106)
	at com.sforce.cd.apexUnit.client.codeCoverage.OAuthTokenGenerator.doPostAndGetOrgToken(OAuthTokenGenerator.java:68)
	at com.sforce.cd.apexUnit.client.codeCoverage.OAuthTokenGenerator.getOrgToken(OAuthTokenGenerator.java:55)
	at com.sforce.cd.apexUnit.client.codeCoverage.CodeCoverageComputer.calculateAggregatedCodeCoverageUsingToolingAPI(CodeCoverageComputer.java:124)
	at com.sforce.cd.apexUnit.ApexUnitRunner.main(ApexUnitRunner.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)

**Comment by glang** [comment]
Great! Thanks for providing this info. So one fix that we have found for users that are running to the TLS issue is as you have deduced in a previous comment -- use Java 8. We recommend setting $JAVA_HOME to Java 8, and the TSL issue should be resolved. Just to be sure, you have pulled the latest version of this project, correct? One way to check is to see if in the pom.xml file, the version is now 2.3.5

**Comment by glang** [comment]
@Kxa422 Have you had the chance to check if using Java 8 resolved the issue?

**Comment by Kxa422** [comment]
I've used a java 1.8 on the server, still the same issue.
My guessing over here is that the code that is failing try to write in a folder without having permission to do so.
When I'm using it on a Windows machine, it's working fine, when I'm on the server (Linux), it's failing.

**Comment by glang** [comment]
@Kxa422 Interesting. Would you be able to modify the permissions of the folders on your server and let us know if that resolves the issue when you get the chance to? :)

**Comment by glang** [comment]
@Kxa422 Would you like for us to setup a time for a google hangout so that we could get to the bottom of the issue in one go, hopefully?
